### ISSUE TITLE
接口开关怎么实现？

### ISSUE THREAD

**Issue by ghost** [Yaccc/-Question#2]
是这样的，我目前知道的系统接口有两种形式，一种是固定uri，用serviceName传参来确定调用的服务；第二种是通过不同uri来实现。
我现在的问题是，怎么去实现一个接口开关。以第一种接口服务为例，我维护了一个服务注册类，该类中只有一个map类型的变量，key是serviceName，value是服务类。服务类有serviceName和开关表示，以及remark注释信息。在spring初始化时，在application中存放服务注册类对象。通过拦截器来存放第一次访问的接口服务以及判断接口开关状态，开关通过页面或接口来控制。
现在问题是，拦截器中，拦截到关闭，我想要返回一个固定的result对象，要怎么来？拦截发在pre阶段，这里spring只会返回boolean类型，我在请求关闭关闭状态的服务就会被catch到异常

**Comment by Yaccc** [comment]
@tks6754 请详细描述下你的问题，看完了但是无法理解你到底要做一个什么东西？

**Comment by ghost** [comment]
@Yaccc 简单的说，就是可以手动控制接口的开放和关闭

**Comment by Yaccc** [comment]
@tks6754 不太理解，你这个是SOA架构下的服务吗？想要手动关系服务提供的接口？

**Comment by ghost** [comment]
@Yaccc 不是。没有涉及SOA架构。比如说，我项目的服务地址是 http://xxx.com/query.do，它有get.user.info和 get.user.cash 两个服务，我怎么控制这两个接口对外开放和关闭。开放就正常返回请求result正常结果，关闭就返回result接口关闭的结果。大概这么个情景

**Comment by Yaccc** [comment]
@tks6754 你这个其实可以说成是HTTP方向的服务治理，如果要简单点做，你就让这两个URL都指向一个接口实例就好了，然后有一个你可以在线更改的状态来控制是返回真的是业务逻辑调用还是返回null。
```java
@url(''/query.do'')
public Result something(){
   if(condition){
//真实业务
   }else{
returen new Result();
}
}
```
至于如何实时的控制变量，简单点你就写一个接口改变就行。大型点就可以看看类似实时配置中心 比如disconf diamond等等

**Comment by ghost** [comment]
@Yaccc 3q。我有思路了。之前把服务开关控制在interceptor，是逻辑有问题。应该放到service里去处理

**Comment by Yaccc** [comment]
@tks6754 恩，重新启一个接口专门修改状态就够了
