### ISSUE TITLE
组装json

### ISSUE THREAD

**Issue by ghost** [Yaccc/-Question#3]
这样一个表
—————————————
name    |   value    |    parnet
  a1       |     xxx      |       null
  a2       |      xxx     |       null
  a3       |      xxx     |       null
  b1       |      yyy     |       a2
   b2      |      yyy     |       a2
  b3       |      yyy     |       a3
   c1      |       zzz     |      b3
   c2      |       zzzz    |      b3
   c3      |     zzzz      |      b3

大概就是这么个父子关系，想组成一个多级节点的json。有什么好办法吗？
自己写的把自己绕进去了。。。

**Comment by Yaccc** [comment]
根据父子关系生成树就行了啊，不会的话可以看看数据结构@tks6754

**Comment by ghost** [comment]
@Yaccc 能不能写个demo看看。我也是这么个思路

**Comment by ghost** [comment]
@Yaccc 。。。忘了这里，之前已经我搞定了
